# .streamlit/secrets.toml
OPENAI_API_KEY = "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"

